# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------

library("checkmate")
library("OpenML")
library("mlr")
library("BatchJobs")
library("rpart")

# Random bot account
saveOMLConfig(apikey = "b3a1ccb9bedf60d842b48b67209f842e", overwrite=TRUE)

setOMLConfig(verbosity = 0)
setOMLConfig(confirm.upload = FALSE)
configureMlr(show.info = FALSE)

# Number of jobs generated by iteration
n.jobs = 1000

# pre-selected mlr learners
pre.selected.lrns = c("classif.randomForest", "classif.svm", "classif.gbm",
    "classif.J48", "classif.ada", "classif.avNNet", "classif.IBk", "classif.PART", 
    "classif.boosting") 

# Implemented but not added: "classif.rpart"

# TODO: add ranger?
# TODO: add gxboost?

# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------