# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------

# Number of jobs generated by iteration
n.jobs = 1000

# pre-selected mlr learners
pre.selected.lrns = c("classif.randomForest", "classif.svm", "classif.rpart", "classif.gbm",
    "classif.J48", "classif.ada", "classif.avNNet", "classif.IBk", "classif.PART", "classif.boosting") 

# TODO: add ranger?
# TODO: add gxboost?

# -------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------
